dist: trusty
sudo: false

language: ruby
rvm:
  - 2.2.2
cache: bundler

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer --assume-extension --check-html --disable-external ./_site --file-ignore /lectures/f16/,/lectures/w17/,/lectures/f17/,/lectures/w18/,/archive/

# --file-ignore /lectures/f16/
# Resolves
#   ./_site/lectures/f16/week1.html
#   *  Tag stdio.h invalid (line 78)
# As the checker doesn't properly ignore textarea contents. Couldn't figure
# out how to do this finer grained. Need to ignore weeks 1, 3, and 6

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

notifications:
  slack:
    secure: NPl/WIA1wXPBYRz+f8RRfKtX0TM+Mq8gla4q9eOo4g37+GRLKlaDVIQh6IrfaLq6g6+gvTY3vRtvFYU0ZpSQBUK9UQ73PU3NVUNBpUuDI/T7F7m4ktSnVcqax5Itef3jKyi/TQCKCW1/EvujuWW4RfN1j3fZkq0S6/ISF7U847ct13Ou3zHiyZhGEppCJI1g0EFlNuQybo19V+AtGJb1NSX5HRVuiL+A2B4T+I80/eXPrbcfSmLG+y2jbwIrCotmUyZf/WUEZBwZ4JmqCiTvImfZ2yNqaDlZu1UFcvlQA9zD2olZozA8tmfoFcdddOtbtR8/6a6dv7QBj3VJA6+AK8LFHqF/HuHSBLaERo2+OoSyjD6xSB9YrrKV9pQpF6pzhHtkzqDzZj9l0kFh0GNTMgtYzxFmGW3X/MWtaXo6ufxka4P0y7UoaesolnshqJVI/cuyWgGOx/VkhpipQSeMDKg0VeIlWOWrQXXxao+h7vuw08qtgbel7n2pdIx3YNSov/66Lu/Hh9VEIBFXj3DFbkPxYDhsRp/6XieyZbN8PBggNB64UHBTkYkXgf93Wu7O2eRtaH4nFbxnDXsDbXGzItv8/nEqxgvSDDi06QH87BumZi3npEUbIRLfVi/c5/3+ZO6BQzXPfTFi1qQR+5HjPJtYrZm9xRMPcsh441YupnU=
  email:
    recipients:
      - c4cs-staff@umich.edu
      
